  
# 核心任务

- name: splunk
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
  
 

  roles:
    - {role: role_common, tags: "role_common"}  
    - {role: splunk, tags: "splunk"}

