  
# 核心任务

- name: splunk
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
  
 

  roles:
    - {role: role_common, tags: "role_common"} 
    - {role: role_nginx, tags: "role_nginx"} 
    - {role: splunk, tags: "splunk"}
    - {role: role_preend, tags: "preend"}
#   - {role: role_end, tags: "role_end"}