# Install splunk

- name: Download splunk
  shell:
  args:
    cmd: wget "https://download.splunk.com/products/splunk/releases/{{splunk_download_version}}/linux/splunk-{{splunk_download_version}}-a6754d8441bf-linux-2.6-amd64.deb"
    chdir: /opt 

- name: Install splunk
  shell: 
  args:
    cmd: dpkg -i splunk-{{splunk_download_version}}-a6754d8441bf-linux-2.6-amd64.deb
    chdir: /opt


- name: Delete splunk rpm
  shell: rm -rf splunk*.deb