# Install splunk

- name: Download and Install splunk
  shell: |
    wget "https://download.splunk.com/products/splunk/releases/{{splunk_download_version}}/linux/splunk-{{splunk_download_version}}-a6754d8441bf-linux-2.6-amd64.deb"
  args:
    cmd:  dpkg -i splunk-{{splunk_download_version}}-a6754d8441bf-linux-2.6-amd64.deb
    chdir: /opt 

