#Install splunk

- name: Download splunk
  shell: 
    wget "https://download.splunk.com/products/splunk/releases/{{splunk_download_version}}/linux/splunk-{{splunk_download_version}}-a6754d8441bf-linux-2.6-x86_64.rpm"
  args:
    chdir: /opt

- name: Install splunk
  shell: 
  args:
    cmd: rpm -i splunk-{{splunk_download_version}}-a6754d8441bf-linux-2.6-x86_64.rpm
    chdir: /opt
    
  


https://download.splunk.com/products/splunk/releases/8.0.4.1/linux/splunk-8.0.4.1-a6754d8441bf-linux-2.6-x86_64.rpm
https://download.splunk.com/products/splunk/releases/8.0.4.1/linux/splunk-8.0.4.1-ab7a85abaa98-linux-2.6-x86_64.rpm
